export const statusStyle = {
    'ACTIVE': 'bg-green-100 text-green-700',
    'LOW STOCK': 'bg-orange-100 text-orange-600',
    'OUT OF STOCK': 'bg-red-100 text-red-600',
};

export const products = [
    {
        id: 1,
        name: 'Neo Blaze Runner',
        category: 'Footwear',
        subcategory: 'Sports',
        sku: 'SKU-BR-061',
        stock: 45,
        price: 129,
        status: 'ACTIVE',
        image: 'https://picsum.photos/seed/shoe1/60/60',
    },
    {
        id: 2,
        name: 'Zenith Smart Watch',
        category: 'Gadgets',
        subcategory: 'Electronics',
        sku: 'SKU-ZW-042',
        stock: 12,
        price: 299,
        status: 'LOW STOCK',
        image: 'https://picsum.photos/seed/watch1/60/60',
    },
    {
        id: 3,
        name: 'Aura ANC Headphones',
        category: 'Audio',
        subcategory: 'Accessories',
        sku: 'SKU-AU-112',
        stock: 120,
        price: 45,
        status: 'ACTIVE',
        image: 'https://picsum.photos/seed/head1/60/60',
    },
    {
        id: 4,
        name: 'Lumina 2.0 Camera',
        category: 'Photography',
        subcategory: '',
        sku: 'SKU-LC-908',
        stock: 0,
        price: 550,
        status: 'OUT OF STOCK',
        image: 'https://picsum.photos/seed/cam1/60/60',
    },
    {
        id: 5,
        name: 'Vertex Gaming Mouse',
        category: 'Accessories',
        subcategory: 'Gaming',
        sku: 'SKU-GM-221',
        stock: 78,
        price: 59,
        status: 'ACTIVE',
        image: 'https://picsum.photos/seed/mouse1/60/60',
    },
    {
        id: 6,
        name: 'Orion Mechanical Keyboard',
        category: 'Accessories',
        subcategory: 'Gaming',
        sku: 'SKU-KB-567',
        stock: 18,
        price: 120,
        status: 'LOW STOCK',
        image: 'https://picsum.photos/seed/keyboard1/60/60',
    },
    {
        id: 7,
        name: 'Nimbus Hoodie',
        category: 'Fashion',
        subcategory: 'Clothing',
        sku: 'SKU-HD-333',
        stock: 200,
        price: 39,
        status: 'ACTIVE',
        image: 'https://picsum.photos/seed/hoodie1/60/60',
    },
    {
        id: 8,
        name: 'AeroFit Backpack',
        category: 'Bags',
        subcategory: 'Travel',
        sku: 'SKU-BP-888',
        stock: 5,
        price: 89,
        status: 'LOW STOCK',
        image: 'https://picsum.photos/seed/bag1/60/60',
    },
    {
        id: 9,
        name: 'Pulse Wireless Earbuds',
        category: 'Audio',
        subcategory: 'Electronics',
        sku: 'SKU-EB-654',
        stock: 0,
        price: 75,
        status: 'OUT OF STOCK',
        image: 'https://picsum.photos/seed/earbuds1/60/60',
    },
    {
        id: 10,
        name: 'Titan Office Chair',
        category: 'Furniture',
        subcategory: 'Office',
        sku: 'SKU-CH-999',
        stock: 32,
        price: 199,
        status: 'ACTIVE',
        image: 'https://picsum.photos/seed/chair1/60/60',
    },
];